#!/bin/bash

#SBATCH --job-name=move_images_template

#SBATCH --mail-user=rafe.lafrance@ufl.edu
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=/blue/guralnick/rafe.lafrance/phenobase/logs/%x_%j.out

#SBATCH --cpus-per-task=1
#SBATCH --mem=4gb
#SBATCH --time=4:00:00

date;hostname;pwd

export PATH=/blue/guralnick/rafe.lafrance/.conda/envs/vitmae/bin:$PATH

module purge
mkdir -p /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3

cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057291070_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1061097756_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1062496106_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057040550_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057015990_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057297925_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1065618515_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091289176_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1091165191_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057353427_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057244644_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078839699_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1078800821_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057220451_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1064687588_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057572145_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057615976_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1088887086_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057405870_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056742214_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057567975_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1078833320_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056899009_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056715269_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1057527366_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057577244_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057062556_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056895864_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057024337_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1078794900_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057052381_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056878318_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1091199428_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056951726_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1091227417_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1061257587_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056841610_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057579530_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1086581769_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057155891_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1065617994_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1091322614_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056951690_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091287060_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1088886609_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1064684577_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057510602_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056834703_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056801308_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056963129_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057191562_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1060362923_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057383906_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057054910_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056931926_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056867405_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057394404_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1086587943_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057636248_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056978745_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057323704_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056880383_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057139295_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1088885781_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057280491_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091195346_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057057188_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057579166_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057311761_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091245282_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056869778_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057008303_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057058777_4.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1065618204_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057221004_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1077080188_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091243536_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057036406_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091144054_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056761696_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057068429_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056894955_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1088885286_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057596775_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056862694_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1064687713_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057454079_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057511386_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057047733_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091119188_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057629278_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056670291_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1057212973_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1077070391_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057144627_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056838948_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091308697_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1091179277_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1065618033_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1062494752_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1061258158_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056920013_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057443846_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1088882964_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1061258090_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078822110_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1065618132_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056951096_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057318697_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057309160_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057047332_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078802347_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057213319_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057447081_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1062494694_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056684430_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091146124_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056725867_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057131338_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056643908_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057372138_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1091217580_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057353576_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057492234_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078854967_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057474086_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056890503_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1084009948_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056801240_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057138746_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1091160308_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056913075_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1078798505_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057112771_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057339112_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057486150_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056763414_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057440704_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1078822462_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1061257695_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056885243_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057415315_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057602065_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057558736_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057375405_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091227804_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056876531_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1065616076_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1062496345_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078833528_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057280851_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1065617610_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1088884061_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091245093_4.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091169728_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056813643_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091196273_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1064685742_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1086710436_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1091123566_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1061257834_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091205155_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056995570_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1078841371_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057578793_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1091284482_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078822976_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056742115_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1091240340_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1065617287_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1078818647_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1086580030_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056672172_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078829159_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057373637_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1064687718_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056929177_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056680470_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057187049_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056757295_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1065616634_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057246453_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057495498_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057605756_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1078797556_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057609991_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1091240881_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057147769_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1078818269_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057376431_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1084009925_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1078815767_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1078795396_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057313985_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078841673_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057362607_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1078831999_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057330409_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057509771_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056714648_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057275019_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091228209_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1061255200_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056744744_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1078794775_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056951730_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078829208_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056783048_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057307059_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091248757_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057500153_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1062494806_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056981034_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056877323_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091130757_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056844469_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057389153_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057641508_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057413150_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057545082_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056724278_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057504825_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1064686728_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057383366_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1064686048_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057288128_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057056986_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1065615450_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056832831_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056838551_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091270518_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1061257433_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057136090_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057156494_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057530317_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056840904_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056749393_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057152600_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056958648_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1065617372_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057232115_4.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056780357_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057398982_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057608000_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056921328_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078837597_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056750657_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1057278412_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1078828736_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057470729_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056795027_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057379843_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1057231922_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057609423_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056738327_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091215848_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056733980_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1078823402_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1056660760_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057637864_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056920987_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091140035_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057115804_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1078840584_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057415149_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057155099_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056972845_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057203829_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057067335_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057221095_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1088887653_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1064684685_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1078843991_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1091163913_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1077080485_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056690069_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056674468_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1086587916_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078840246_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056853108_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057360299_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057534034_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1064684671_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1062494707_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056951019_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091302481_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1065618097_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078826125_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056876324_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056901889_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056970829_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091149162_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1065615572_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091159125_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1057226653_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078841731_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1091251596_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1078832556_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057328646_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057558222_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1061255665_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091149077_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056785956_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057570287_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057479982_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1091149702_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056683995_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056806691_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1056781469_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057152687_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1057146094_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091134109_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1091217021_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057025223_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057339257_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1088886299_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1064684919_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1086594657_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057426822_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057003790_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1061253162_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057357405_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1061255516_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078818188_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056913511_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1065616477_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057542189_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1057257014_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1091186486_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057225636_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057045438_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056921355_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056827085_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057324154_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1078795305_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057439242_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057301474_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1077080539_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057371125_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091118909_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057553218_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1077071598_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056673298_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056811262_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1057165255_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1078825342_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056734010_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1091305582_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057528031_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1091146958_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1078828222_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1091213435_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1061258112_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057037941_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1056842015_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1086587934_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056838146_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056951375_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056867671_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1078833168_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056851169_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056951262_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1057047116_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091157159_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1078833299_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1091274451_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1065617697_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056855723_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091191688_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1091316783_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1088887194_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1091305195_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057573266_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0074a/1056751142_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1061257875_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1056971341_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1091222589_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056727897_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1065618222_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1091317999_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057342145_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1056810489_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1056638125_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1056985918_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1056710417_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1091310725_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1057455230_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057183651_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057528892_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0004/1056930427_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1057089296_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1056809175_3.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1056998351_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057457832_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0034a/1061254215_1_small.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1057470873_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1091216617_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1057216951_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0003/1057366252_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0086a/1060289038_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3

tar czf /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3.tgz /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_inference_fract3
