#!/bin/bash

#SBATCH --job-name=move_images_template

#SBATCH --mail-user=rafe.lafrance@ufl.edu
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=/blue/guralnick/rafe.lafrance/phenobase/logs/%x_%j.out

#SBATCH --cpus-per-task=1
#SBATCH --mem=4gb
#SBATCH --time=4:00:00

date;hostname;pwd

export PATH=/blue/guralnick/rafe.lafrance/.conda/envs/vitmae/bin:$PATH

module purge
mkdir -p /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample

cp /blue/guralnick/share/phenobase_specimen_data/images/images_0081h/1846508503_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0191g/3357425712_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0006/1929987017_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0152d/1929354624_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0138d/1990012853_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0170i/1269646695_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0260h/2234416655_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0192a/4077970859_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0208e/2012885753_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0310b/1319337200_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/1990212722_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0169h/4536542797_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0171f/3344418604_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0236g/1503202251_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/4101935538_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0152d/1928481761_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0332c/2234415903_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/2234439854_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0018b/1978010434_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0127e/2234415406_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0357d/2242404542_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0094d/3331189078_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0344f/4855961955_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0079i/2012881265_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0026j/3091255926_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0211j/4072330682_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0272i/2517116137_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0051j/2859452166_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0199c/1586166409_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0105i/2234441596_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0345a/2234439546_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/4078026573_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0038g/1269646666_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0278i/2273380407_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1928210568_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0059c/2421673110_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0269e/437052967_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1990013028_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0248e/4154093523_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/1977808638_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0080b/2234442571_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0325f/4536617787_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0180c/1319988391_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0056e/4102405863_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/4072331085_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0330a/2234414363_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/4075444703_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0244d/3766337486_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0261f/1320414006_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0114i/2234416783_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0008a/1929665131_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0360c/2234416083_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0342e/4022424666_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0266b/2234415821_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0275e/4850316648_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0293c/2234415291_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0350a/2234443703_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0192a/4077971790_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/3897108875_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0177h/438051128_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0299f/4102298560_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0192a/4075457162_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0078j/3091302293_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0304c/2234416353_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0113g/1657211243_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0185h/4855961944_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0113g/1426380013_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0182i/1269701233_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1849165375_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0101b/2234414955_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0239e/437195658_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/1930533799_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0199c/1269710057_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0163e/2234347187_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0042d/4022428654_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0142f/2807598244_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0342e/3709936750_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0200d/1929058376_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0083g/1321040186_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0308e/3978726588_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/3969736700_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0216e/2234415500_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0156j/3829950581_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0154f/2517147181_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0093g/1426300944_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0032f/1039018182_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0079i/2012879015_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0027f/4911348654_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0247h/2234441044_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0335j/1849133358_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0260h/1928482672_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0300e/3709815902_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0129j/3969635715_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0203g/3925863780_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1426380044_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0244d/3709835710_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0250c/2807584277_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0249j/1321107427_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0204c/1320922695_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0136i/4876070975_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0045h/1929751834_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0116g/1657211239_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0007b/2012883320_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0127e/2418030542_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0294e/3969830414_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0257c/3336596458_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0232d/4088573299_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0101b/2234417736_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0231c/2859442993_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0029e/4072330672_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0050d/3344418599_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0105i/2421675790_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0350a/1990238264_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0075e/4072527133_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0338d/3344499341_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0067b/2012883807_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0070d/3969541704_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0186a/4077964860_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0110i/2234439625_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0303a/1990012953_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0233e/4536617777_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/2234441789_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0105i/2012878679_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0308e/3709836378_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0231c/2565960782_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0216e/2234441600_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0355c/2012877529_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0065i/1990012893_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0263j/1318383696_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0256d/3925864479_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/1846508777_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1977808815_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0173j/4072325683_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0153g/3925863055_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0262e/4536542775_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0322d/3382281361_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0105i/1990212760_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0183e/2234416171_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0102a/1503207086_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0338d/2859480573_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0169h/4855961511_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0021f/623648224_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0274h/1989552897_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0101b/2012882191_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0127e/2234443595_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0173j/3469893397_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0201e/2234414696_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0097c/2270180810_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0348c/1990212759_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0203g/3357422913_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0053b/2012881467_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0342e/3798068850_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0203g/3962219388_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0085c/2807329097_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0229a/1930572385_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0332c/2012876787_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0173j/3498204636_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0300e/3978717010_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0319b/3886936752_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0045h/1978010282_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3391076303_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1318523746_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0345a/2234416384_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0262e/4911348706_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0136i/4876070920_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0211j/3744712870_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0177h/4436958757_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0305g/4911348793_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0210d/1990212793_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0308e/4072330801_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0304c/1929892746_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0143j/3357422778_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0353e/3925832321_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0320a/2234417022_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1990012948_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0343j/1319489832_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0250c/3382281360_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0092b/1927956812_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1457777885_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0018b/1929073859_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0358b/4102306587_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0304c/1990012913_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/4022428653_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0014d/3359178301_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0008a/1988874696_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0162i/623648226_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0239e/439050386_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0010d/3969544706_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0267a/1930774886_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0330a/1977996165_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0046e/4101998247_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0354b/4022429656_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0053b/1977996162_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0319b/3925832316_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0329f/437511819_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0300e/3886951931_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0364c/1990012814_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0336e/3969736702_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0079i/2012877099_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0118j/4064853900_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/1928177082_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0291a/1978889256_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0143j/3469835265_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0256d/3969602187_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0310b/3766338345_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0084j/2565964191_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0359j/1318582870_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0168g/3969781435_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0264c/3331189850_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0019c/2573389060_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/2234415805_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0129j/3469841222_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0101b/2012885067_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0296f/4134275607_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0173j/4072579358_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/2234415067_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0060d/3695155086_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0308e/3709901159_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0066f/4898127409_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0096e/4443340357_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1317846705_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0179d/1930830639_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0336e/4095744371_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0264c/2859444009_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0134a/4101936539_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0111a/1426300957_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0080b/2234443453_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0236g/1426300834_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0356a/1978010469_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0170i/1317421015_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0360c/1929095958_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0209c/1321111179_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0329f/4443341369_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0327b/4095542261_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0239e/4850314703_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0349e/3695155328_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3469895471_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0232d/3893486494_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0208e/2234416658_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0192a/4095732123_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0271g/1426300898_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0191g/3969852332_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0264c/2859405039_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0319b/3709990759_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0143j/3344418563_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0007b/2012877066_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0270f/1269646709_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/1990012928_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0092b/2234414577_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0121f/2807577274_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0040e/4077971852_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0330a/2270596510_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0279f/1317974761_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0188d/1990012984_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3969729702_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0092b/2234416034_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0348c/1457774139_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0088e/4101946596_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0250c/2573385909_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0158b/4876025505_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0025i/2234415860_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0144i/4912220640_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0073f/4922184403_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/2012876797_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0281c/2807391348_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0159f/2859418179_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0119a/4101946551_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0047a/1319543374_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/4022429643_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0270f/1319993491_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0131i/4912221815_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/1929735043_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0199c/1318981588_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0032f/4855961910_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0354b/4077970860_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0077d/3710044256_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1322216175_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0179d/1978010387_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0344f/4102415429_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0274h/2234443330_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0294e/3969541712_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0216e/2012878931_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/3469894504_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0181g/3969578404_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0146e/2012875218_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0075e/4101976912_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0088e/4072330596_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0006/1990012761_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0191g/3925863122_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0161c/1423966622_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0053b/1978010411_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0260h/1929350981_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0222e/4855961977_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0211j/3969740835_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0036i/2234442707_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0096e/4134261757_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0009c/3331182435_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0203g/3695155335_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0248e/439050390_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0163e/2234442131_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0065i/2234416571_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/2234414125_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0280a/1990238232_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0112b/2234443615_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/3766338337_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0137b/4850316574_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/3969729704_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/4101936527_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0021f/4850316582_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0197d/1929574977_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0143j/3709887018_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0346d/2807287863_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0116g/1426300930_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0267a/1998749592_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0023d/3925864453_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0334f/4102134606_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3344499118_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0089i/2234441726_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0067b/1990012996_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0021f/4876028498_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/4072330932_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0274h/1990012936_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0360c/2234415692_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0353e/4072331099_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0276b/2012876821_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0333b/1319124189_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0283g/1457825641_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0314c/2234416754_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0089i/2012884302_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0071h/1846553314_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0187j/3969740830_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0344f/4102306579_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0239e/4850316738_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0259i/2273381177_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0307f/4536542776_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0127e/2234415442_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0334f/4851121449_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0345a/2234416154_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3710004387_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0314c/1990012940_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0063j/2565962693_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0306j/1322634359_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0066f/4876025491_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0100i/2421731846_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/1998801374_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0049f/4850316591_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/3709817446_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0153g/3925864487_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0320a/2515037195_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0256d/3766337495_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0212g/3865343056_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0053b/1929133109_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0254b/2270271029_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0361a/2234442015_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0300e/4072331116_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0342e/3744712981_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0327b/3925832307_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0346d/3091272295_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0122d/1928107766_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0324c/1930209271_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0352d/3091298044_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0026j/3091241962_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0106a/1269710050_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0104h/1929333748_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0205d/1990012920_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0306j/1457792264_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0146e/2012883494_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0082e/4064853896_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0248e/4850316715_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0341b/3893486458_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0061a/1426300975_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0080b/2234414207_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0251f/1317473442_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0024h/1977996005_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1038999148_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0093g/1457749422_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0053b/1849174526_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0021f/4898082639_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0119a/4092871110_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0196a/4102134612_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/4102006441_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0312a/1990012908_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/3698756944_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0054g/1318783690_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0344f/437190613_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0340c/2012879536_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0201e/2234414754_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0342e/3698757067_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/2234441530_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0126h/4536542774_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0196a/4102298576_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0095a/1426300984_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0310b/4850316314_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/4022425655_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0017a/1457811723_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0304c/2234441319_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0294e/4078024796_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0259i/2514208702_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0126h/4102326467_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0168g/4072330953_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0056e/4092871178_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0046e/4404891608_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0118j/4072330722_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0098h/1930443377_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0173j/4022429654_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0141h/4855961872_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/4067769322_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0314c/1891107246_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0012a/1990212728_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0210d/1846549671_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0364c/2234415435_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0018b/2242402978_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0146e/2242404504_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0037b/2012878808_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0212g/3496971658_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0145a/4102418540_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0195h/4078037862_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0114i/2012885892_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0117j/3969577346_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0150i/1317411426_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0107b/1990238275_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0157i/4922202283_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0322d/3427865021_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0244d/3886962587_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0299f/4876028500_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0029e/4102377257_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0261f/1317779178_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0129j/3766337448_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0124g/3866884602_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0029e/438855287_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0139g/3709853822_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0008a/1990013026_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0276b/2012880781_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0213c/1318021312_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0007b/2012877502_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0243a/1929915122_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0124g/3698765453_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0348c/2234417339_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/3698765504_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0148f/3091298065_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0326j/1318423669_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0142f/3091272298_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0255a/1929412260_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0175f/2516125050_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0115b/2012886480_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0235h/2012885386_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0160h/4102306581_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0250c/3091304487_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0361a/2234441836_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0328e/3709951758_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0124g/3925832324_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0036i/2234441500_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0036i/2012881148_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0189h/4095542067_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0211j/3893486735_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0103g/1319050007_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/3969597220_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0284e/4922188858_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0253e/4922190062_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0193j/3925832305_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0348c/2012876066_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/4064895432_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0058h/1840496494_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0325f/4102166421_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0141h/4102418532_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0267a/1928601437_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0013b/2234416886_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0141h/4095776324_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0249j/1320449359_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0110i/2234303477_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0031d/3469932248_2.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0120a/4536617784_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0124g/3925863082_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0303a/1978010441_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0108g/1320917799_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0323e/4022425642_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0052i/2234415257_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0099d/3766337438_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0305g/4922188859_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0247h/2234415804_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0140c/1426300904_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0134a/4134261753_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0319b/3978718982_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0315e/3744712869_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0268d/4101980820_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0171f/2573386781_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0194e/2012878391_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0310b/623648187_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0339f/437717816_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0054g/1320038303_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0272i/2514202708_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0253e/4899970937_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0135f/2807431248_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0202j/3435796469_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0116g/1426301051_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0207g/3470666539_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0021f/1038998690_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0110i/1990012997_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0306j/1319395769_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
cp /blue/guralnick/share/phenobase_specimen_data/images/images_0266b/2012878793_1.jpg /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample

tar czf /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample.tgz /blue/guralnick/rafe.lafrance/phenobase/data/images/flower_neg_sample
